package io.github.yashkasera.alohomora.showcaseApp

import androidx.compose.ui.test.assertCountEquals
import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.hasAnyAncestor
import androidx.compose.ui.test.hasTestTag
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.onNodeWithTag
import androidx.test.ext.junit.runners.AndroidJUnit4
import io.github.yashkasera.alohomora.ui.testing.AlohomoraTestTags.Chrome
import io.github.yashkasera.alohomora.ui.testing.AlohomoraTestTags.Config
import io.github.yashkasera.alohomora.ui.testing.AlohomoraTestTags.GitHistory
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Config and Git History with a populated build config — coverage that is impossible from
 * `:alohomora`.
 *
 * Both screens read `Alohomora.config`, which `AlohomoraInitializer` discovers through
 * `ServiceLoader`. The implementation it looks for is generated by the Alohomora Gradle plugin, and
 * `:alohomora` does not apply that plugin to itself: there is no `META-INF/services` entry anywhere
 * in that module, so its own device tests can only ever assert the null-config shape — see
 * `ConfigAndGitHistoryTest`, which pins the `--not-set--` fallback and the "No Commits Available"
 * empty state. `showcaseApp` applies the plugin for the `debug` variant, which is the variant
 * `androidTest` compiles against. This is the only place the populated path exists.
 *
 * Values are asserted by shape, not by content. The branch, the sha and the commit list are whatever
 * the working tree held when the APK was built, so pinning any of them would fail on the next
 * commit. What is worth pinning is that they are there at all.
 */
@RunWith(AndroidJUnit4::class)
class ConfigAndGitHistoryE2ETest : ShowcaseE2ETest() {

    @Test
    fun noBuildInfoCellFallsBackToNotSet() {
        openConfig()

        // `InfoItem` renders the literal "--not-set--" for a null value. With a discovered config
        // all six cells have one, including Build Time — the timestamp the Gradle task stamps in
        // milliseconds, which `DateUtils` then formats rather than skipping.
        compose.onAllNodes(
            hasText("--not-set--") and hasAnyAncestor(hasTestTag(Config.BUILD_INFO)),
            useUnmergedTree = true,
        ).assertCountEquals(0)
    }

    @Test
    fun buildVariantIsTheDebugVariantUnderTest() {
        openConfig()

        // The plugin's `enabledVariants` is `setOf("debug")` and androidTest compiles against the
        // tested debug variant, so this cell also checks that the two agree.
        compose.onNode(
            hasText("debug") and hasAnyAncestor(hasTestTag(Config.info("Build Variant"))),
            useUnmergedTree = true,
        ).assertExists()
    }

    /** `ConfigScreen` renders this section inside `Alohomora.config?.let`, so it is a null check. */
    @Test
    fun theEnvironmentSectionIsRenderedBecauseAConfigWasDiscovered() {
        openConfig()

        compose.onNodeWithTag(Config.ENVIRONMENT).assertIsDisplayed()
    }

    @Test
    fun gitHistoryListsTheCommitsEmbeddedAtBuildTime() {
        openGitHistory()

        // The list and the empty state are the two branches of one `if`, so the presence of either
        // is the absence of the other.
        compose.onNodeWithTag(Chrome.EMPTY_STATE).assertDoesNotExist()
    }

    @Test
    fun gitHistoryReportsANonEmptyCommitCount() {
        openGitHistory()

        // Asserted negatively. `maxCommits = 50` caps the list and a shallow CI clone can hand the
        // task fewer, so the count is not knowable — only that it is not zero. This is not implied
        // by the test above: the list branch also renders while `isLoading` is still true, with
        // nothing in it.
        compose.onAllNodes(
            hasText("SHOWING LAST 0 COMMITS") and hasTestTag(Chrome.TOP_BAR_SUBTITLE),
        ).assertCountEquals(0)
    }

    private fun openConfig() {
        compose.openConsole()
        compose.openModule("Config")
        compose.awaitTag(Config.BUILD_INFO)
    }

    private fun openGitHistory() {
        compose.openConsole()
        compose.openModule("GitHistory")
        compose.awaitTag(GitHistory.LIST)
    }
}
