package io.github.yashkasera.alohomora.ui.theme.themes

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import io.github.yashkasera.alohomora.ui.theme.AlohomoraColorTheme

val MonochromeLightTheme = AlohomoraColorTheme(
    id = "monochrome",
    displayName = "Monochrome",
    isDark = false,
    materialColorScheme = lightColorScheme(
        primary = Color(0xFF000000),
        onPrimary = Color(0xFFDFE0FF),
        primaryContainer = Color(0xFF1125AD),
        onPrimaryContainer = Color(0xFFFFFFFF),
        inversePrimary = Color(0xFFBCC2FF),
        secondary = Color(0xFF5E5E5E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFD4D4D4),
        onSecondaryContainer = Color(0xFF1B1B1B),
        tertiary = Color(0xFF3B3B3B),
        onTertiary = Color(0xFFE2E2E2),
        tertiaryContainer = Color(0xFF747474),
        onTertiaryContainer = Color(0xFFFFFFFF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF9F9F9),
        onBackground = Color(0xFF1B1B1B),
        surface = Color(0xFFF9F9F9),
        onSurface = Color(0xFF1B1B1B),
        surfaceVariant = Color(0xFFE2E2E2),
        onSurfaceVariant = Color(0xFF474747),
        surfaceTint = Color(0xFF3F4FD0),
        inverseSurface = Color(0xFF303030),
        inverseOnSurface = Color(0xFFF1F1F1),
        outline = Color(0xFF777777),
        outlineVariant = Color(0xFFC6C6C6),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFFF9F9F9),
        surfaceContainer = Color(0xFFEEEEEE),
        surfaceContainerHigh = Color(0xFFE8E8E8),
        surfaceContainerHighest = Color(0xFFE2E2E2),
        surfaceContainerLow = Color(0xFFF3F3F3),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceDim = Color(0xFFDADADA),
    ),
    accent = Color(0xFF6366F1),
    success = Color(0xFF059669),
    successContainer = Color(0x1F059669),
    warning = Color(0xFFD97706),
    info = Color(0xFF1976D2),
    fatal = Color(0xFF9C27B0),
)

val MonochromeDarkTheme = AlohomoraColorTheme(
    id = "monochrome",
    displayName = "Monochrome",
    isDark = true,
    materialColorScheme = darkColorScheme(
        primary = Color(0xFFFFFFFF),
        onPrimary = Color(0xFF1B1B1B),
        primaryContainer = Color(0xFFD4D4D4),
        onPrimaryContainer = Color(0xFF000000),
        inversePrimary = Color(0xFF5E5E5E),
        secondary = Color(0xFFC6C6C6),
        onSecondary = Color(0xFF1B1B1B),
        secondaryContainer = Color(0xFF474747),
        onSecondaryContainer = Color(0xFFE2E2E2),
        tertiary = Color(0xFFE2E2E2),
        onTertiary = Color(0xFF1B1B1B),
        tertiaryContainer = Color(0xFF919191),
        onTertiaryContainer = Color(0xFF000000),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF131313),
        onBackground = Color(0xFFE2E2E2),
        surface = Color(0xFF131313),
        onSurface = Color(0xFFE2E2E2),
        surfaceVariant = Color(0xFF474747),
        onSurfaceVariant = Color(0xFFC6C6C6),
        surfaceTint = Color(0xFFBCC2FF),
        inverseSurface = Color(0xFFE2E2E2),
        inverseOnSurface = Color(0xFF303030),
        outline = Color(0xFF919191),
        outlineVariant = Color(0xFF474747),
        scrim = Color(0xFF000000),
        surfaceBright = Color(0xFF393939),
        surfaceContainer = Color(0xFF1F1F1F),
        surfaceContainerHigh = Color(0xFF2A2A2A),
        surfaceContainerHighest = Color(0xFF353535),
        surfaceContainerLow = Color(0xFF1B1B1B),
        surfaceContainerLowest = Color(0xFF0E0E0E),
        surfaceDim = Color(0xFF131313),
    ),
    accent = Color(0xFF8394E2),
    success = Color(0xFF34D399),
    successContainer = Color(0x1F34D399),
    warning = Color(0xFFFFC857),
    info = Color(0xFF64B5F6),
    fatal = Color(0xFFCE93D8),
)
