package io.github.yashkasera.alohomora.desktop.data.config

import io.github.yashkasera.alohomora.common.deeplink.DeepLinkDef

/**
 * Renders the deep-link catalog to Markdown, committed back to the repo as `deeplinks/README.md` so the
 * repo itself is the browsable, reviewable catalog. Deterministic: everything is sorted, so it only
 * diffs when the definitions change. A flat alphabetical index sits at the top for plain find-in-page.
 */
object DeepLinkCatalogRenderer {

    fun render(defs: List<DeepLinkDef>): String = buildString {
        appendLine("# Deep link catalog")
        appendLine()
        appendLine("Generated by Alohomora from the deep-link definitions. Do not edit by hand.")
        appendLine()

        appendLine("## Index")
        appendLine()
        defs.sortedBy { it.name.lowercase() }.forEach { def ->
            appendLine("- ${def.name} — `${location(def)}`")
        }
        appendLine()

        defs.groupBy { it.module }.toSortedMap().forEach { (module, moduleDefs) ->
            appendLine("## $module")
            appendLine()
            moduleDefs.sortedBy { it.name.lowercase() }.forEach { def -> appendDef(def) }
        }
    }

    private fun StringBuilder.appendDef(def: DeepLinkDef) {
        appendLine("### ${def.name}")
        def.flow?.let { appendLine("_Flow: ${it}_") }
        if (def.description.isNotBlank()) {
            appendLine()
            appendLine(def.description)
        }
        appendLine()
        appendLine("```")
        appendLine(def.uriTemplate)
        appendLine("```")
        if (def.params.isNotEmpty()) {
            appendLine()
            appendLine("| Param | Type | Required | Allowed | Description |")
            appendLine("| --- | --- | --- | --- | --- |")
            def.params.forEach { p ->
                appendLine(
                    "| ${cell(p.name)} | ${p.type} | ${p.required} | " +
                        "${cell(p.allowedValues.joinToString(", "))} | ${cell(p.description)} |",
                )
            }
        }
        if (def.examples.isNotEmpty()) {
            appendLine()
            appendLine("Examples:")
            def.examples.forEach { appendLine("- `$it`") }
        }
        appendLine()
    }

    private fun location(def: DeepLinkDef): String =
        listOfNotNull(def.module, def.flow).joinToString("/")

    /** Escapes a Markdown table cell: pipes would start a new column, newlines would break the row. */
    private fun cell(value: String): String =
        value.replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").replace("\r", " ")
}
