package io.github.yashkasera.alohomora.device

import androidx.compose.ui.test.assertIsDisplayed
import androidx.compose.ui.test.assertTextContains
import androidx.compose.ui.test.assertTextEquals
import androidx.compose.ui.test.hasAnyAncestor
import androidx.compose.ui.test.hasTestTag
import androidx.compose.ui.test.hasText
import androidx.compose.ui.test.junit4.createComposeRule
import androidx.compose.ui.test.onNodeWithTag
import io.github.yashkasera.alohomora.presentation.navigation.Routes
import io.github.yashkasera.alohomora.ui.testing.AlohomoraTestTags.Chrome
import io.github.yashkasera.alohomora.ui.testing.AlohomoraTestTags.Config
import org.junit.Rule
import org.junit.Test

/**
 * Config and Git History with no build metadata — which is the only state they can be in here.
 *
 * Both screens read `Alohomora.config`, and in *this* APK it is null. `AlohomoraInitializer`
 * discovers the config through `ServiceLoader`, and the implementation it looks for is generated by
 * the Alohomora Gradle plugin, which `:alohomora` does not apply to itself: there is no
 * `META-INF/services` entry anywhere in this module. `GitHistoryViewModel` reads
 * `Alohomora.config?.commits.orEmpty()`, and `ConfigScreen` hands `Alohomora.config?.toBuildMetadata()`
 * — null — to the build-info grid.
 *
 * That makes the populated case untestable from here, not merely unwritten. It is covered from
 * `:showcaseApp`, where the plugin *is* applied. Asserting the empty shape here is still worth
 * doing: a null config is what every consumer sees before they add the plugin, and rendering
 * "--not-set--" rather than crashing is the behaviour that keeps a first-run console usable.
 */
class ConfigAndGitHistoryTest {

    @get:Rule(order = 0)
    val console = ConsoleTestRule()

    @get:Rule(order = 1)
    val compose = createComposeRule()

    @Test
    fun configRendersItsTopBarTitle() {
        compose.launchConsole(Routes.Config)

        compose.onNodeWithTag(Chrome.TOP_BAR_TITLE).assertTextEquals("Config")
    }

    @Test
    fun theBuildInfoSectionIsRendered() {
        compose.launchConsole(Routes.Config)

        compose.onNodeWithTag(Config.BUILD_INFO).assertIsDisplayed()
    }

    @Test
    fun everyBuildInfoCellFallsBackToNotSet() {
        compose.launchConsole(Routes.Config)

        // `InfoItem` renders the literal "--not-set--" for a null value, and with no config every
        // one of the five is null — including Build Time, whose formatter is skipped entirely
        // rather than being handed a zero timestamp.
        listOf("Branch", "Build Variant", "Version Name", "Version Code", "Build Time", "Commit Hash")
            .forEach { label ->
                compose.onNode(
                    hasText("--not-set--") and hasAnyAncestor(hasTestTag(Config.info(label))),
                    useUnmergedTree = true,
                ).assertExists()
            }
    }

    @Test
    fun theEnvironmentSectionIsAbsentWithoutAConfig() {
        compose.launchConsole(Routes.Config)

        compose.onNodeWithTag(Config.ENVIRONMENT).assertDoesNotExist()
    }

    @Test
    fun gitHistoryRendersItsEmptyState() {
        compose.launchConsole(Routes.GitHistory)

        compose.onNodeWithTag(Chrome.EMPTY_STATE).assertIsDisplayed()
        compose.onNodeWithTag(Chrome.EMPTY_STATE_TITLE).assertTextContains("No Commits Available")
    }

    @Test
    fun gitHistoryReportsAnEmptyCommitCount() {
        compose.launchConsole(Routes.GitHistory)

        compose.onNodeWithTag(Chrome.TOP_BAR_SUBTITLE).assertTextEquals("SHOWING LAST 0 COMMITS")
    }
}
